CREATE ROLE IF NOT EXISTS REMITTANCE_DBT_ROLE;

GRANT USAGE ON WAREHOUSE REMITTANCE_DBT_WH TO ROLE REMITTANCE_DBT_ROLE;
GRANT SELECT ON DATABASE REMITTANCE_CORRIDOR TO ROLE REMITTANCE_DBT_ROLE;
GRANT CREATE SCHEMA ON DATABASE REMITTANCE_CORRIDOR TO ROLE REMITTANCE_DBT_ROLE;

GRANT USAGE ON SCHEMA REMITTANCE_CORRIDOR.RAW TO ROLE REMITTANCE_DBT_ROLE;
GRANT SELECT ON ALL TABLE IN SCHEMA REMITTANCE_CORRIDOR.RAW TO ROLE REMITTANCE_DBT_ROLE;
GRANT SELECT ON ALL FUTURE TABLE IN SCHEMA REMITTANCE_CORRIDOR.RAW TO ROLE REMITTANCE_DBT_ROLE;

GRANT ROLE REMITTANCE_DBT_ROLE TO USER MUGO;
GRANT ROLE REMITTANCE_DBT_ROLE TO USER REMITTANCE_CI_USER;