-- Step 1: create prod schemas and a dedicated prod role, scoped only to them.
-- Mirrors the DEV_*/REMITTANCE_DBT_ROLE pattern but kept separate for
-- least-privilege isolation between CI/dev and the real prod dbt job.

CREATE SCHEMA IF NOT EXISTS REMITTANCE_CORRIDOR.PROD_STAGING;
CREATE SCHEMA IF NOT EXISTS REMITTANCE_CORRIDOR.PROD_INTERMEDIATE;
CREATE SCHEMA IF NOT EXISTS REMITTANCE_CORRIDOR.PROD_MARTS;
CREATE SCHEMA IF NOT EXISTS REMITTANCE_CORRIDOR.PROD_REFERENCE;

CREATE ROLE IF NOT EXISTS REMITTANCE_PROD_ROLE;

GRANT USAGE ON DATABASE REMITTANCE_CORRIDOR TO ROLE REMITTANCE_PROD_ROLE;
GRANT USAGE ON WAREHOUSE REMITTANCE_CORRIDOR_WH TO ROLE REMITTANCE_PROD_ROLE;

GRANT ALL ON SCHEMA REMITTANCE_CORRIDOR.PROD_STAGING TO ROLE REMITTANCE_PROD_ROLE;
GRANT ALL ON SCHEMA REMITTANCE_CORRIDOR.PROD_INTERMEDIATE TO ROLE REMITTANCE_PROD_ROLE;
GRANT ALL ON SCHEMA REMITTANCE_CORRIDOR.PROD_MARTS TO ROLE REMITTANCE_PROD_ROLE;
GRANT ALL ON SCHEMA REMITTANCE_CORRIDOR.PROD_REFERENCE TO ROLE REMITTANCE_PROD_ROLE;

-- dbt also needs SELECT on RAW to build staging models from it
GRANT USAGE ON SCHEMA REMITTANCE_CORRIDOR.RAW TO ROLE REMITTANCE_PROD_ROLE;
GRANT SELECT ON ALL TABLES IN SCHEMA REMITTANCE_CORRIDOR.RAW TO ROLE REMITTANCE_PROD_ROLE;
GRANT SELECT ON FUTURE TABLES IN SCHEMA REMITTANCE_CORRIDOR.RAW TO ROLE REMITTANCE_PROD_ROLE;